#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start() {
	rfc=4096
	threads="$(grep -c "processor" "/proc/cpuinfo")"
	rps_mask="$(printf '%x' $(( (1 << threads) - 1 )))"

	sysctl -w net.core.rps_sock_flow_entries="$(( rfc * threads ))"

	for fileRps in /sys/class/net/eth*/queues/rx-*/rps_cpus; do
		[ -f "$fileRps" ] && echo "$rps_mask" > "$fileRps"
	done

	for fileRfc in /sys/class/net/eth*/queues/rx-*/rps_flow_cnt; do
		[ -f "$fileRfc" ] && echo "$rfc" > "$fileRfc"
	done

	uci set network.@globals[0].packet_steering="1"
	uci commit network

	for i in /sys/class/net/eth*; do
		[ -d "$i" ] || continue
		i="${i##*/}"
		ethtool -K "$i" rx-checksum on tx-scatter-gather on gso on tso on ufo on
		ethtool -K "$i" tx-checksum-ip-generic on || {
			ethtool -K "$i" tx-checksum-ipv4 on tx-checksum-ipv6 on
		}
	done
} >"/dev/null" 2>&1
